---
name: gitlab

instance_groups:
- name: docker
  azs: [z1]
  instances: 1
  persistent_disk: 65536
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: ca_certs
    release: os-conf
    properties:
      certs: ((/concourse/main/bosh_ca_cert))
  - name: docker
    release: docker
    properties:
      tcp_address: 0.0.0.0
      tls_cacert: "((docker-tls.ca))"
      tls_cert: "((docker-tls.certificate))"
      tls_key: "((docker-tls.private_key))"
  - name: containers
    release: docker
    properties:
      containers:
        - name: gitlab
          image: "bosh/gitlab-ce"
          bind_ports:
            - "443:443"
            - "80:80"
          bind_volumes: [ /var/opt/gitlab ]
          volumes: [ "/usr/local/share/ca-certificates:/etc/gitlab/trusted-certs" ]
          # env_vars:
          dockerfile: |
            FROM gitlab/gitlab-ce
            RUN echo " \n\
              gitlab_rails['omniauth_enabled'] = true \n\
              gitlab_rails['omniauth_allow_single_sign_on'] = ['oauth2_generic'] \n\
              gitlab_rails['omniauth_block_auto_created_users'] = false \n\
              gitlab_rails['omniauth_providers'] = [ \n\
                { \n\
                  'name' => 'oauth2_generic', \n\
                  'app_id' => 'gitlab', \n\
                  'app_secret' => 'foobar', \n\
                  'args' => { \n\
                    client_options: { \n\
                      'site' => 'https://192.168.50.6:8443', # including port if necessary \n\
                      'user_info_url' => '/userinfo' \n\
                    }, \n\
                    user_response_structure: { \n\
                      #root_path: ['data', 'user'], # i.e. if attributes are returned in JsonAPI format (in a 'user' node nested under a 'data' node) \n\
                      attributes: { nickname: 'user_name' } # if the nickname attribute of a user is called 'username' \n\
                    }, \n\
                    # optionally, you can add the following two lines to 'white label' the display name \n\
                    # of this strategy (appears in urls and Gitlab login buttons) \n\
                    # If you do this, you must also replace oauth2_generic, everywhere it appears above, with the new name.  \n\
                 #   name: 'Satorix', # display name for this strategy \n\
                  #  strategy_class: 'OmniAuth::Strategies::OAuth2Generic', # Devise-specific config option Gitlab uses to find renamed strategy \n\
                    redirect_url: 'http://10.244.0.2/users/auth/oauth2_generic/callback' \n\
                  } \n\
                } \n\
              ] \n\
              " >> /opt/gitlab/etc/gitlab.rb.template
            RUN cat /opt/gitlab/etc/gitlab.rb.template


variables:
- name: docker-ca
  type: certificate
  options:
    is_ca: true
    common_name: dockerCA
- name: docker-tls
  type: certificate
  options:
    ca: docker-ca
    common_name: docker
    extended_key_usage:
    - client_auth

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: false

releases:
- name: os-conf
  version: 19
  url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=19
  sha1: f515406949ee0bba0329d1ce4a7eb1679521eabd
- name: docker
  version: 31.0.1
  url: https://github.com/cloudfoundry-community/docker-boshrelease/releases/download/v31.0.1/docker-31.0.1.tgz
  sha1: 550ab08cb6dcd113ab5182d84fbcb09d966a612a
