groups:
- name: main
  jobs:
  - unit-tests
  - load-tests
  - promote-new-version

resources:
- name: concourse-pipeline-samples
  type: git
  source:
    branch: master
    uri: https://github.com/starkandwayne/cfsummit-labs.git
- name: load-test-app-manifest
  type: file
  source:
    filename: manifest.yml
    content:
      applications:
      - name: load-test-((pws-app-suffix))
        command: node index.js
        buildpack: https://github.com/cloudfoundry/buildpack-nodejs.git
        instances: 1
        hostname: load-test-((pws-app-suffix))
- name: prod-app-manifest
  type: file
  source:
    filename: manifest.yml
    content:
      applications:
      - name: ((pws-app-suffix))
        command: node index.js
        buildpack: https://github.com/cloudfoundry/buildpack-nodejs.git
        instances: 1
        hostname: ((pws-app-suffix))
- name: PWS
  type: cf
  source:
    api: ((pws-api))
    organization: ((pws-organization))
    username: ((deploy-username))
    password: ((deploy-password))
    skip_cert_check: true
    space: ((pws-space))

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: concourse-pipeline-samples
    trigger: true
  - task: run-unit-tests
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/unit-tests.yml

- name: load-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: load-test-app-manifest
    - get: concourse-pipeline-samples
      trigger: true
      passed: [ unit-tests ]
  - put: PWS
    params:
      manifest: load-test-app-manifest/manifest.yml
      path: concourse-pipeline-samples/blue-green-app-deployment/bgd-app
  - task: run-load-tests
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/load-tests.yml
    params:
      APP_URL: http://load-test-((pws-app-suffix)).((pws-app-domain))
# TODO: delete app after succefull test      


- name: promote-new-version
  serial: true
  public: true
  plan:
  - aggregate:
    - get: prod-app-manifest
    - get: concourse-pipeline-samples
      trigger: true
      passed: [ load-tests ]
  - put: PWS
    params:
      manifest: prod-app-manifest/manifest.yml
      path: concourse-pipeline-samples/blue-green-app-deployment/bgd-app
      current_app_name: ((pws-app-suffix))

resource_types:
- name: file
  type: docker-image
  source:
    repository: aequitas/concourse-file-resource
